swagger: '2.0'
info:
  version: '1.0.0'
  title: Milcare Foundations Onlus API
  description: This is an open API for Milcare Foundations Onlus website developed by Sophisticated Kids team
  termsOfService: All the material on the website is for educational purpose only, any commercial use is prohibited.
  contact:
    name: Sophisticated Kids
    url:  https://gitlab.com/alaamjadi/HSK
  license: 
    name: MIT
    url: http://opensource.org/licenses/MIT
host: sophisticatedkids.herokuapp.com
schemes:
  - 'https'
  - 'http'
basePath: '/api'
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: Events
    description: 'Related to the events'
  - name: Services
    description: 'Related to the services'
  - name: Staff
    description: 'Related to the staff members'
paths:
  /events:
    get:
      tags:
        - Events
      operationId: getEvents
      summary: Event names and short descriptions
      description: 'Returns the names, short descriptions, and UUIDS of all events'
      parameters:
        - name: offset
          in: query
          description: Pagination offset. Default is 0.
          type: integer
        - name: limit
          in: query
          description: Maximum number of items per page. Default is 20 and cannot exceed 100.
          type: integer 
      responses:
        '200':
          description: Collection of events
          schema:
            $ref: '#/definitions/events'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
      x-swagger-router-controller: Event
  /events/{eventId}:
    get:
      tags:
        - Events
      operationId: getEvent
      summary: Finds an event by ID
      description: returns an event
      parameters:
        - name: eventId
          in: path
          description: ID of event to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/event'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
  /services:
    get:
      tags:
        - Services
      operationId: getServices
      summary: Service names and short descriptions
      description: 'Returns the names, short descriptions, and UUIDS of all services'
      parameters:
        - name: offset
          in: query
          description: Pagination offset. Default is 0.
          type: integer
        - name: limit
          in: query
          description: Maximum number of items per page. Default is 20 and cannot exceed 100.
          type: integer
      responses:
        '200':
          description: Collection of services
          schema:
            $ref: '#/definitions/services'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
  /services/{serviceId}:
    get:
      tags:
        - Services
      operationId: getService
      summary: Finds a service by ID
      description: returns a service
      parameters:
        - name: serviceId
          in: path
          description: ID of service to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/service'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
  /staff:
    get:
      tags:
        - Staff
      operationId: getStaff
      summary: Staff names and roles
      description: 'Returns the names, and UUIDS of all staff'
      parameters:
        - name: offset
          in: query
          description: Pagination offset. Default is 0.
          type: integer
        - name: limit
          in: query
          description: Maximum number of items per page. Default is 20 and cannot exceed 100.
          type: integer
      responses:
        '200':
          description: Collection of staff
          schema:
            $ref: '#/definitions/staff'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
  /staff/{staffId}:
    get:
      tags:
        - Staff
      operationId: getMember
      summary: Finds a staff member by ID
      description: returns a staff member
      parameters:
        - name: staffId
          in: path
          description: ID of staff member to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/member'
        default:
          description: Unexpected error!
          schema:
            $ref: '#/definitions/Error'
definitions:
  events:
    type: array
    items:
      $ref: '#/definitions/event'
  event:
    properties:
      uuid:
        type: string
        description: Universally Unique Identifier for the event
      title:
        type: string
        example: Spring event
      date:
        type: string
        format: date-time
        example: '2020-05-16'
      location:
        type: string
        example: Piazza Leonardo da vinci
      summary:
        type: string
        example: 'The new autumn socializing workshop organized by the Lu.VI Onlus Foundation will be presented.'
      description:
        type: string
        example: 'An appointment which over time has found more and more interest and that is why this fourth edition in 2019 had to be split into two separate workshops: Workshop on Tuesday and that the Wednesday in order to accommodate all the applications received.'
      image:
        type: string
        example: 'https://sophisticatedkids.heroku.com/assets/img/events_spring.jpg'
      organizer:
        $ref: '#/definitions/staff'
      presents:
        $ref: '#/definitions/services'
  services:
    type: array
    items:
      $ref: '#/definitions/service'
  service:
    properties:
      uuid:
        type: string
        description: Universally Unique Identifier for the service
      title:
        type: string
        example: Hospice service
      summary:
        type: string
        example: 'The Hospice can accommodate 12 Patients with advanced diseases.'
      description:
        type: string
        example: 'The Hospice Milcare is a house with open windows on the world, where some sick people have accepted to live with dignity the final stage of their lives, assisted by their family members and social and health operators trained. The old farmhouse, now abandoned, has been restored to Milano Care as our (Milcare Onlus) for the community.'
      image:
        type: string
        example: 'https://sophisticatedkids.heroku.com/assets/img/events_spring.jpg'
      presented:
        $ref: '#/definitions/events'
      server:
        $ref: '#/definitions/staff'
  staff:
    type: array
    items:
      $ref: '#/definitions/member'
  member:
    properties:
      uuid:
        type: string
        description: Universally Unique Identifier for the member
      name:
        type: string
        example: Bruno Andreoni 
      role:
        type: string
        example: President
      description:
        type: string
        example: 'He is the president of Milcare. Bruno studied engineering at Polimi.'
      image:
        type: string
        example: 'https://sophisticatedkids.heroku.com/assets/img/member_bruno-Andreoni.jpg'
      organizes:
        $ref: '#/definitions/events'
      serves:
        $ref: '#/definitions/services'
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string