swagger: '2.0'
info:
  version: 1.0.0
  title: Milcare Foundations Onlus
  description: This is an open API for Milcare Foundations Onlus website developed by Sophisticated Kids team
  termsOfService: All the material on the website is for educational purpose only, any commercial use is prohibited.
  license: 
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost
basePath: /v1
tags:
  - name: Events
  - name: Services
  - name: Staff
paths:
  /events:
    get:
      summary: All events
      description: You can get all the available events provided by Milcare sorted by their dates from the oldest to the newest
      tags:
        - Events
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          type: integer
          description: Maximum number of items per page
      responses:
        200:
          description: Collection of events
          schema:
            type: array
            items:
              $ref: '#/definitions/event'
        400:
          description: Invalid!
        404:
          description: Unexpected error!
  
  /events/{eventId}:
    get:
      summary: Finds an event by ID
      tags:
        - Events
      description: returns an event
      produces:
        - application/json
      parameters:
        - name: eventId
          in: path
          description: ID of event to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/event'
        '400':
          description: Invalid ID supplied
        '404':
          description: Event not found

  /services:
    get:
      summary: All services
      description: You can get all the available services provided by Milcare
      tags:
        - Services
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          type: integer
          description: Maximum number of items per page
      responses:
        200:
          description: Collection of services
          schema:
            type: array
            items:
              $ref: '#/definitions/service'
        400:
          description: Invalid!
        404:
          description: Unexpected error!
          
  /services/{serviceId}:
    get:
      summary: Finds an service by ID
      tags:
        - Services
      description: returns an service
      produces:
        - application/json
      parameters:
        - name: serviceId
          in: path
          description: ID of service to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/service'
        '400':
          description: Invalid ID supplied
        '404':
          description: Service not found

  /staff:
    get:
      summary: All staff members
      description: You can get all the staff members who work Milcare
      tags:
        - Staff
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          type: integer
          description: Maximum number of items per page
      responses:
        200:
          description: Collection of staff members
          schema:
            type: array
            items:
              $ref: '#/definitions/member'
        400:
          description: Invalid!
        404:
          description: Unexpected error!
  
  /staff/{staffId}:
    get:
      summary: Finds an staff by ID
      tags:
        - Staff
      description: returns an staff
      produces:
        - application/json
      parameters:
        - name: staffId
          in: path
          description: ID of staff to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/member'
        '400':
          description: Invalid ID supplied
        '404':
          description: Staff not found

definitions:
  event:
    title: Event
    description: A Milcare event
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: 
        type: string
        example: Spring event
      presenter:
        $ref: '#/definitions/member'
      service:
        $ref: '#/definitions/service'
      date:
        type: string
        example: '2020-05-09'
      location:
        type: string
        example: Piazza Leonardo da vinci
        
  member:
    title: Staff Member
    description: A staff member of Milcare
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Andrea Broni
      role:
        type: string
        example: President
      information:
        type: string
        example: Studied at POLIMI and he is successful
      event:
        $ref: '#/definitions/event'
      service:
        $ref: '#/definitions/service'
      
  service:
    title: Service
    description: A service of Milcare
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Hospice
      information:
        type: string
        example: Hospice is one our services
      member:
        $ref: '#/definitions/member'
      event:
        $ref: '#/definitions/event'
